name: polesearcherapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.4.0+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.11.0
  hooks_riverpod: ^0.6.1

  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.2.11
  toggle_switch: ^1.2.0

  responsive_framework: ^0.0.14
  package_info: ^0.4.3
  sprintf: 4.0.0

  url_launcher: 5.7.10
  map_launcher: ^1.1.3+1
  google_maps_flutter: 0.5.28
  flutter_picker: 1.1.0
  flutter_datetime_picker: 1.4.0

  firebase_core: 0.7.0
  firebase_auth: 0.20.0
  firebase_storage: ^7.0.0
  cloud_firestore: 0.16.0+1

  app_settings: 4.0.4
  permission_handler: ^5.0.1+1
  image_picker: 0.6.7+12
  photo_view: 0.10.2
  cached_network_image: 2.2.0+1
  flutter_swiper: 1.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # geolocator
  geolocator: ^6.1.6
  geocoding: ^1.0.5
  flutter_geofence: ^0.4.1
  flutter_local_notifications: ^0.5.1
  provider: ^6.0.0
  flutter_parsed_text: ^2.2.1
  transparent_image: ^2.0.0
  analyzer: ^0.41.2
  firebase_admin: ^0.1.4

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

  pedantic: any

dependency_overrides:
  intl: any

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/hokuriku/icon1.png"
  image_path_ios: "assets/hokuriku/icon_ios1.png"

flutter_native_splash:
  image: "assets/hokuriku/splash1.png"
  color: "4274B1"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #assets:
  #  - assets/icon.jpg
  #  - assets/icon2.jpg
  #  - assets/illust3482_thumb.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
